# Generated by Django 2.2.6 on 2020-01-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dept_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(choices=[('dept', 'DEPT'), ('auth', 'authotiry')], max_length=10)),
                ('dname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='auth_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Authority', models.CharField(choices=[('', 'DEPT'), ('auth', 'authotiry')], max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dept', models.ManyToManyField(to='app.dept_model')),
            ],
        ),
    ]
